# Generated by Django 3.1.7 on 2021-03-03 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
            ],
        ),
        migrations.CreateModel(
            name='UrlsModel',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.basemodel')),
                ('low_url', models.URLField(verbose_name='Low quality Element URL')),
                ('med_url', models.URLField(verbose_name='Med quality Element URL')),
                ('high_url', models.URLField(verbose_name='High quality Element URL')),
                ('max_url', models.URLField(verbose_name='Max quality Element URL')),
            ],
            bases=('api.basemodel',),
        ),
        migrations.CreateModel(
            name='VideosModel',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.basemodel')),
                ('uid', models.CharField(max_length=300, unique=True, verbose_name='Video Unique ID')),
                ('url', models.URLField(verbose_name='Video URL')),
                ('title', models.CharField(max_length=300, verbose_name='Video title')),
                ('uploader', models.CharField(max_length=300, verbose_name='Uploader Name')),
                ('views_count', models.IntegerField(verbose_name='Views count')),
                ('audios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audios', to='api.urlsmodel', verbose_name='Audios List')),
                ('thumbs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thumbs', to='api.urlsmodel', verbose_name='Thumbs List')),
                ('videos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='api.urlsmodel', verbose_name='Videos List')),
            ],
            bases=('api.basemodel',),
        ),
    ]
