# Generated by Django 3.1.7 on 2021-03-10 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210303_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlsmodel',
            name='high_url',
            field=models.TextField(verbose_name='High quality Element URL'),
        ),
        migrations.AlterField(
            model_name='urlsmodel',
            name='low_url',
            field=models.TextField(verbose_name='Low quality Element URL'),
        ),
        migrations.AlterField(
            model_name='urlsmodel',
            name='max_url',
            field=models.TextField(verbose_name='Max quality Element URL'),
        ),
        migrations.AlterField(
            model_name='urlsmodel',
            name='med_url',
            field=models.TextField(verbose_name='Med quality Element URL'),
        ),
        migrations.AlterField(
            model_name='videosmodel',
            name='uid',
            field=models.CharField(max_length=300, unique=True, verbose_name='UID'),
        ),
    ]
